### ISSUE TITLE
DLL not found in android build (for VR)

### ISSUE THREAD

**Issue by JensDijkgraaf** [DIAOZHUO/SileroVADForUnity#1]
@DIAOZHUO 
I have tried using the VAD in unity and it works great! Thanks for the work you put in. However, I am trying to use it in my VR application, and when I build the application and run it on my headset, I get the following error:
Error Unity DllNotFoundException: Unable to load DLL 'onnxruntime'. Tried the load the following dynamic libraries: Unable to load dynamic library 'onnxruntime' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "onnxruntime" not found

I have tried researching some things on the internet but I can not seem to find any solution. Have you had any encounters with this or do you have any suggestion for me to fix it? I hope you can help!

**Comment by DIAOZHUO** [comment]
Hi, 
This project uses [Microsoft.ML.OnnxRuntime](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime) for neural network computing. 

Microsoft.ML.OnnxRuntime plugin needs to be placed in Plugins/ONNX. And set it to the correct platform in Unity editor.


In this project, I only add plugins for windows and mac. The plugin for Android and IOS can be found by downloading from the link above, and then finding the file after extracting it.

**Comment by JensDijkgraaf** [comment]
Hi,
thanks for the quick response! That worked pretty well, however when build for android, I now had the issue of not being able to find the silero model on the headset because of the streamingassets path, which is not working correctly on android. But I have made a script to ensure the streamingassets path is copied to a literal path and that worked, so now everything is working well. Thanks for the help and your project!

**Comment by Karamela134** [comment]
> made a script to ensure the streamingassets path is copied to a literal path

Hello, can you please elaborate on how you did this ?

**Comment by JensDijkgraaf** [comment]
> > made a script to ensure the streamingassets path is copied to a literal path
> 
> Hello, can you please elaborate on how you did this ?

Yes sure! This is the exact script i have used to ensure that it worked on my VR headset.

```
public class FileExtractor : MonoBehaviour
{
    private IEnumerator Start()
    {
        yield return EnsureFileExtracted();
    }

    private IEnumerator EnsureFileExtracted()
    {
        string persistentDirectory = Path.Combine(Application.persistentDataPath, "Model");
        string persistentPath = Path.Combine(persistentDirectory, "silero_vad.onnx");

        if (!File.Exists(persistentPath))
        {
            string streamingPath = Path.Combine(Application.streamingAssetsPath, "Model/silero_vad.onnx");            
            using (UnityWebRequest request = UnityWebRequest.Get(streamingPath))
            {
                yield return request.SendWebRequest();
                
                if (request.result != UnityWebRequest.Result.Success)
                {
                    Debug.LogError("Failed to load file: " + request.error);
                }
                else
                {
                    // Ensure the directory exists
                    Directory.CreateDirectory(persistentDirectory);
                    
                    File.WriteAllBytes(persistentPath, request.downloadHandler.data);
                }
            }
        }
    }
}
```

This basically creates a new directory in the persistent data path to copy the file from the streaming assets, which ensures the headset can open it. I had not figured out why the streamingassets did not work on the VR headset, but I am guessing it has something to do with scoping.

**Comment by Karamela134** [comment]
Thanks a lot for your swift and thorough answer. I'll look into it. 

If you would be so nice to help me with including the Android library from the link provided above by OP. I'm a complete newbie when it comes to stuff this far and "astray" from the Unity field if you know what I mean. I got STOMPED trying to do it for Android and ended up missing up my whole project. 

So If you will take me by the hand and explain in detail, as possible as you please, how I'd get it to work on Android I'll be much much grateful.

**Comment by Karamela134** [comment]
> The plugin for Android and IOS can be found by downloading from the link above, and then finding the file after extracting it.

Can you please help me with more details on this ? I couldn't find any .DLL in the link you provided.
